name = "instant-income-hub"
main = "src/server.ts"
compatibility_date = "2026-09-22"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "instant-income-db"
database_id = "2a60d0cb-a22e-4d31-95f1-0d7a65e5dbeb"

[observability]
enabled = true
