/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ApiPublicFeedKindRouteImport } from './routes/api/public/feed.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedKindRoute = ApiPublicFeedKindRouteImport.update({
  id: '/api/public/feed/$kind',
  path: '/api/public/feed/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/offers': typeof OffersRoute
  '/wallet': typeof WalletRoute
  '/watch': typeof WatchRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/offers': typeof OffersRoute
  '/wallet': typeof WalletRoute
  '/watch': typeof WatchRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/offers': typeof OffersRoute
  '/wallet': typeof WalletRoute
  '/watch': typeof WatchRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/offers' | '/wallet' | '/watch' | '/api/public/feed/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/offers' | '/wallet' | '/watch' | '/api/public/feed/$kind'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/offers'
    | '/wallet'
    | '/watch'
    | '/api/public/feed/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OffersRoute: typeof OffersRoute
  WalletRoute: typeof WalletRoute
  WatchRoute: typeof WatchRoute
  ApiPublicFeedKindRoute: typeof ApiPublicFeedKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feed/$kind': {
      id: '/api/public/feed/$kind'
      path: '/api/public/feed/$kind'
      fullPath: '/api/public/feed/$kind'
      preLoaderRoute: typeof ApiPublicFeedKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OffersRoute: OffersRoute,
  WalletRoute: WalletRoute,
  WatchRoute: WatchRoute,
  ApiPublicFeedKindRoute: ApiPublicFeedKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
