/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiPostbackRouteImport } from './routes/api/postback'
import { Route as ApiPostbackAdgemRouteImport } from './routes/api/postback.adgem'
import { Route as ApiPostbackCpagripRouteImport } from './routes/api/postback.cpagrip'
import { Route as ApiPostbackCpaleadRouteImport } from './routes/api/postback.cpalead'
import { Route as ApiUserBalanceRouteImport } from './routes/api/user/balance'
import { Route as ApiUserSessionRouteImport } from './routes/api/user/session'
import { Route as ApiUserWithdrawRouteImport } from './routes/api/user/withdraw'
import { Route as ApiPublicFeedKindRouteImport } from './routes/api/public/feed.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostbackRoute = ApiPostbackRouteImport.update({
  id: '/api/postback',
  path: '/api/postback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostbackAdgemRoute = ApiPostbackAdgemRouteImport.update({
  id: '/adgem',
  path: '/adgem',
  getParentRoute: () => ApiPostbackRoute,
} as any)
const ApiPostbackCpagripRoute = ApiPostbackCpagripRouteImport.update({
  id: '/cpagrip',
  path: '/cpagrip',
  getParentRoute: () => ApiPostbackRoute,
} as any)
const ApiPostbackCpaleadRoute = ApiPostbackCpaleadRouteImport.update({
  id: '/cpalead',
  path: '/cpalead',
  getParentRoute: () => ApiPostbackRoute,
} as any)
const ApiUserBalanceRoute = ApiUserBalanceRouteImport.update({
  id: '/api/user/balance',
  path: '/api/user/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSessionRoute = ApiUserSessionRouteImport.update({
  id: '/api/user/session',
  path: '/api/user/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserWithdrawRoute = ApiUserWithdrawRouteImport.update({
  id: '/api/user/withdraw',
  path: '/api/user/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedKindRoute = ApiPublicFeedKindRouteImport.update({
  id: '/api/public/feed/$kind',
  path: '/api/public/feed/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wallet': typeof WalletRoute
  '/api/postback': typeof ApiPostbackRouteWithChildren
  '/api/postback/adgem': typeof ApiPostbackAdgemRoute
  '/api/postback/cpagrip': typeof ApiPostbackCpagripRoute
  '/api/postback/cpalead': typeof ApiPostbackCpaleadRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/session': typeof ApiUserSessionRoute
  '/api/user/withdraw': typeof ApiUserWithdrawRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wallet': typeof WalletRoute
  '/api/postback': typeof ApiPostbackRouteWithChildren
  '/api/postback/adgem': typeof ApiPostbackAdgemRoute
  '/api/postback/cpagrip': typeof ApiPostbackCpagripRoute
  '/api/postback/cpalead': typeof ApiPostbackCpaleadRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/session': typeof ApiUserSessionRoute
  '/api/user/withdraw': typeof ApiUserWithdrawRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wallet': typeof WalletRoute
  '/api/postback': typeof ApiPostbackRouteWithChildren
  '/api/postback/adgem': typeof ApiPostbackAdgemRoute
  '/api/postback/cpagrip': typeof ApiPostbackCpagripRoute
  '/api/postback/cpalead': typeof ApiPostbackCpaleadRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/session': typeof ApiUserSessionRoute
  '/api/user/withdraw': typeof ApiUserWithdrawRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wallet'
    | '/api/postback'
    | '/api/postback/adgem'
    | '/api/postback/cpagrip'
    | '/api/postback/cpalead'
    | '/api/user/balance'
    | '/api/user/session'
    | '/api/user/withdraw'
    | '/api/public/feed/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wallet'
    | '/api/postback'
    | '/api/postback/adgem'
    | '/api/postback/cpagrip'
    | '/api/postback/cpalead'
    | '/api/user/balance'
    | '/api/user/session'
    | '/api/user/withdraw'
    | '/api/public/feed/$kind'
  id:
    | '__root__'
    | '/'
    | '/wallet'
    | '/api/postback'
    | '/api/postback/adgem'
    | '/api/postback/cpagrip'
    | '/api/postback/cpalead'
    | '/api/user/balance'
    | '/api/user/session'
    | '/api/user/withdraw'
    | '/api/public/feed/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WalletRoute: typeof WalletRoute
  ApiPostbackRoute: typeof ApiPostbackRouteWithChildren
  ApiUserBalanceRoute: typeof ApiUserBalanceRoute
  ApiUserSessionRoute: typeof ApiUserSessionRoute
  ApiUserWithdrawRoute: typeof ApiUserWithdrawRoute
  ApiPublicFeedKindRoute: typeof ApiPublicFeedKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/postback': {
      id: '/api/postback'
      path: '/api/postback'
      fullPath: '/api/postback'
      preLoaderRoute: typeof ApiPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/postback/adgem': {
      id: '/api/postback/adgem'
      path: '/adgem'
      fullPath: '/api/postback/adgem'
      preLoaderRoute: typeof ApiPostbackAdgemRouteImport
      parentRoute: typeof ApiPostbackRoute
    }
    '/api/postback/cpagrip': {
      id: '/api/postback/cpagrip'
      path: '/cpagrip'
      fullPath: '/api/postback/cpagrip'
      preLoaderRoute: typeof ApiPostbackCpagripRouteImport
      parentRoute: typeof ApiPostbackRoute
    }
    '/api/postback/cpalead': {
      id: '/api/postback/cpalead'
      path: '/cpalead'
      fullPath: '/api/postback/cpalead'
      preLoaderRoute: typeof ApiPostbackCpaleadRouteImport
      parentRoute: typeof ApiPostbackRoute
    }
    '/api/user/balance': {
      id: '/api/user/balance'
      path: '/api/user/balance'
      fullPath: '/api/user/balance'
      preLoaderRoute: typeof ApiUserBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/session': {
      id: '/api/user/session'
      path: '/api/user/session'
      fullPath: '/api/user/session'
      preLoaderRoute: typeof ApiUserSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/withdraw': {
      id: '/api/user/withdraw'
      path: '/api/user/withdraw'
      fullPath: '/api/user/withdraw'
      preLoaderRoute: typeof ApiUserWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feed/$kind': {
      id: '/api/public/feed/$kind'
      path: '/api/public/feed/$kind'
      fullPath: '/api/public/feed/$kind'
      preLoaderRoute: typeof ApiPublicFeedKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPostbackRouteChildren {
  ApiPostbackAdgemRoute: typeof ApiPostbackAdgemRoute
  ApiPostbackCpagripRoute: typeof ApiPostbackCpagripRoute
  ApiPostbackCpaleadRoute: typeof ApiPostbackCpaleadRoute
}

const ApiPostbackRouteChildren: ApiPostbackRouteChildren = {
  ApiPostbackAdgemRoute: ApiPostbackAdgemRoute,
  ApiPostbackCpagripRoute: ApiPostbackCpagripRoute,
  ApiPostbackCpaleadRoute: ApiPostbackCpaleadRoute,
}

const ApiPostbackRouteWithChildren = ApiPostbackRoute._addFileChildren(
  ApiPostbackRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WalletRoute: WalletRoute,
  ApiPostbackRoute: ApiPostbackRouteWithChildren,
  ApiUserBalanceRoute: ApiUserBalanceRoute,
  ApiUserSessionRoute: ApiUserSessionRoute,
  ApiUserWithdrawRoute: ApiUserWithdrawRoute,
  ApiPublicFeedKindRoute: ApiPublicFeedKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
