/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiPostbackRouteImport } from './routes/api/postback'
import { Route as ApiAdminCashoutsRouteImport } from './routes/api/admin/cashouts'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiPostbackAdgemRouteImport } from './routes/api/postback.adgem'
import { Route as ApiPostbackCpagripRouteImport } from './routes/api/postback.cpagrip'
import { Route as ApiPostbackCpaleadRouteImport } from './routes/api/postback.cpalead'
import { Route as ApiPostbackCpxRouteImport } from './routes/api/postback.cpx'
import { Route as ApiUserBalanceRouteImport } from './routes/api/user/balance'
import { Route as ApiUserCpxUrlRouteImport } from './routes/api/user/cpx-url'
import { Route as ApiUserSessionRouteImport } from './routes/api/user/session'
import { Route as ApiUserWithdrawRouteImport } from './routes/api/user/withdraw'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google.callback'
import { Route as ApiPublicFeedKindRouteImport } from './routes/api/public/feed.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostbackRoute = ApiPostbackRouteImport.update({
  id: '/api/postback',
  path: '/api/postback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCashoutsRoute = ApiAdminCashoutsRouteImport.update({
  id: '/api/admin/cashouts',
  path: '/api/admin/cashouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostbackAdgemRoute = ApiPostbackAdgemRouteImport.update({
  id: '/adgem',
  path: '/adgem',
  getParentRoute: () => ApiPostbackRoute,
} as any)
const ApiPostbackCpagripRoute = ApiPostbackCpagripRouteImport.update({
  id: '/cpagrip',
  path: '/cpagrip',
  getParentRoute: () => ApiPostbackRoute,
} as any)
const ApiPostbackCpaleadRoute = ApiPostbackCpaleadRouteImport.update({
  id: '/cpalead',
  path: '/cpalead',
  getParentRoute: () => ApiPostbackRoute,
} as any)
const ApiPostbackCpxRoute = ApiPostbackCpxRouteImport.update({
  id: '/cpx',
  path: '/cpx',
  getParentRoute: () => ApiPostbackRoute,
} as any)
const ApiUserBalanceRoute = ApiUserBalanceRouteImport.update({
  id: '/api/user/balance',
  path: '/api/user/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCpxUrlRoute = ApiUserCpxUrlRouteImport.update({
  id: '/api/user/cpx-url',
  path: '/api/user/cpx-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSessionRoute = ApiUserSessionRouteImport.update({
  id: '/api/user/session',
  path: '/api/user/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserWithdrawRoute = ApiUserWithdrawRouteImport.update({
  id: '/api/user/withdraw',
  path: '/api/user/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiPublicFeedKindRoute = ApiPublicFeedKindRouteImport.update({
  id: '/api/public/feed/$kind',
  path: '/api/public/feed/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/surveys': typeof SurveysRoute
  '/wallet': typeof WalletRoute
  '/api/postback': typeof ApiPostbackRouteWithChildren
  '/api/admin/cashouts': typeof ApiAdminCashoutsRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/postback/adgem': typeof ApiPostbackAdgemRoute
  '/api/postback/cpagrip': typeof ApiPostbackCpagripRoute
  '/api/postback/cpalead': typeof ApiPostbackCpaleadRoute
  '/api/postback/cpx': typeof ApiPostbackCpxRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/cpx-url': typeof ApiUserCpxUrlRoute
  '/api/user/session': typeof ApiUserSessionRoute
  '/api/user/withdraw': typeof ApiUserWithdrawRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/surveys': typeof SurveysRoute
  '/wallet': typeof WalletRoute
  '/api/postback': typeof ApiPostbackRouteWithChildren
  '/api/admin/cashouts': typeof ApiAdminCashoutsRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/postback/adgem': typeof ApiPostbackAdgemRoute
  '/api/postback/cpagrip': typeof ApiPostbackCpagripRoute
  '/api/postback/cpalead': typeof ApiPostbackCpaleadRoute
  '/api/postback/cpx': typeof ApiPostbackCpxRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/cpx-url': typeof ApiUserCpxUrlRoute
  '/api/user/session': typeof ApiUserSessionRoute
  '/api/user/withdraw': typeof ApiUserWithdrawRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/surveys': typeof SurveysRoute
  '/wallet': typeof WalletRoute
  '/api/postback': typeof ApiPostbackRouteWithChildren
  '/api/admin/cashouts': typeof ApiAdminCashoutsRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/postback/adgem': typeof ApiPostbackAdgemRoute
  '/api/postback/cpagrip': typeof ApiPostbackCpagripRoute
  '/api/postback/cpalead': typeof ApiPostbackCpaleadRoute
  '/api/postback/cpx': typeof ApiPostbackCpxRoute
  '/api/user/balance': typeof ApiUserBalanceRoute
  '/api/user/cpx-url': typeof ApiUserCpxUrlRoute
  '/api/user/session': typeof ApiUserSessionRoute
  '/api/user/withdraw': typeof ApiUserWithdrawRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/feed/$kind': typeof ApiPublicFeedKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/surveys'
    | '/wallet'
    | '/api/postback'
    | '/api/admin/cashouts'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/postback/adgem'
    | '/api/postback/cpagrip'
    | '/api/postback/cpalead'
    | '/api/postback/cpx'
    | '/api/user/balance'
    | '/api/user/cpx-url'
    | '/api/user/session'
    | '/api/user/withdraw'
    | '/api/auth/google/callback'
    | '/api/public/feed/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/surveys'
    | '/wallet'
    | '/api/postback'
    | '/api/admin/cashouts'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/postback/adgem'
    | '/api/postback/cpagrip'
    | '/api/postback/cpalead'
    | '/api/postback/cpx'
    | '/api/user/balance'
    | '/api/user/cpx-url'
    | '/api/user/session'
    | '/api/user/withdraw'
    | '/api/auth/google/callback'
    | '/api/public/feed/$kind'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/surveys'
    | '/wallet'
    | '/api/postback'
    | '/api/admin/cashouts'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/postback/adgem'
    | '/api/postback/cpagrip'
    | '/api/postback/cpalead'
    | '/api/postback/cpx'
    | '/api/user/balance'
    | '/api/user/cpx-url'
    | '/api/user/session'
    | '/api/user/withdraw'
    | '/api/auth/google/callback'
    | '/api/public/feed/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  SurveysRoute: typeof SurveysRoute
  WalletRoute: typeof WalletRoute
  ApiPostbackRoute: typeof ApiPostbackRouteWithChildren
  ApiAdminCashoutsRoute: typeof ApiAdminCashoutsRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiUserBalanceRoute: typeof ApiUserBalanceRoute
  ApiUserCpxUrlRoute: typeof ApiUserCpxUrlRoute
  ApiUserSessionRoute: typeof ApiUserSessionRoute
  ApiUserWithdrawRoute: typeof ApiUserWithdrawRoute
  ApiPublicFeedKindRoute: typeof ApiPublicFeedKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/postback': {
      id: '/api/postback'
      path: '/api/postback'
      fullPath: '/api/postback'
      preLoaderRoute: typeof ApiPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cashouts': {
      id: '/api/admin/cashouts'
      path: '/api/admin/cashouts'
      fullPath: '/api/admin/cashouts'
      preLoaderRoute: typeof ApiAdminCashoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/postback/adgem': {
      id: '/api/postback/adgem'
      path: '/adgem'
      fullPath: '/api/postback/adgem'
      preLoaderRoute: typeof ApiPostbackAdgemRouteImport
      parentRoute: typeof ApiPostbackRoute
    }
    '/api/postback/cpagrip': {
      id: '/api/postback/cpagrip'
      path: '/cpagrip'
      fullPath: '/api/postback/cpagrip'
      preLoaderRoute: typeof ApiPostbackCpagripRouteImport
      parentRoute: typeof ApiPostbackRoute
    }
    '/api/postback/cpalead': {
      id: '/api/postback/cpalead'
      path: '/cpalead'
      fullPath: '/api/postback/cpalead'
      preLoaderRoute: typeof ApiPostbackCpaleadRouteImport
      parentRoute: typeof ApiPostbackRoute
    }
    '/api/postback/cpx': {
      id: '/api/postback/cpx'
      path: '/cpx'
      fullPath: '/api/postback/cpx'
      preLoaderRoute: typeof ApiPostbackCpxRouteImport
      parentRoute: typeof ApiPostbackRoute
    }
    '/api/user/balance': {
      id: '/api/user/balance'
      path: '/api/user/balance'
      fullPath: '/api/user/balance'
      preLoaderRoute: typeof ApiUserBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/cpx-url': {
      id: '/api/user/cpx-url'
      path: '/api/user/cpx-url'
      fullPath: '/api/user/cpx-url'
      preLoaderRoute: typeof ApiUserCpxUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/session': {
      id: '/api/user/session'
      path: '/api/user/session'
      fullPath: '/api/user/session'
      preLoaderRoute: typeof ApiUserSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/withdraw': {
      id: '/api/user/withdraw'
      path: '/api/user/withdraw'
      fullPath: '/api/user/withdraw'
      preLoaderRoute: typeof ApiUserWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/public/feed/$kind': {
      id: '/api/public/feed/$kind'
      path: '/api/public/feed/$kind'
      fullPath: '/api/public/feed/$kind'
      preLoaderRoute: typeof ApiPublicFeedKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPostbackRouteChildren {
  ApiPostbackAdgemRoute: typeof ApiPostbackAdgemRoute
  ApiPostbackCpagripRoute: typeof ApiPostbackCpagripRoute
  ApiPostbackCpaleadRoute: typeof ApiPostbackCpaleadRoute
  ApiPostbackCpxRoute: typeof ApiPostbackCpxRoute
}

const ApiPostbackRouteChildren: ApiPostbackRouteChildren = {
  ApiPostbackAdgemRoute: ApiPostbackAdgemRoute,
  ApiPostbackCpagripRoute: ApiPostbackCpagripRoute,
  ApiPostbackCpaleadRoute: ApiPostbackCpaleadRoute,
  ApiPostbackCpxRoute: ApiPostbackCpxRoute,
}

const ApiPostbackRouteWithChildren = ApiPostbackRoute._addFileChildren(
  ApiPostbackRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  SurveysRoute: SurveysRoute,
  WalletRoute: WalletRoute,
  ApiPostbackRoute: ApiPostbackRouteWithChildren,
  ApiAdminCashoutsRoute: ApiAdminCashoutsRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiUserBalanceRoute: ApiUserBalanceRoute,
  ApiUserCpxUrlRoute: ApiUserCpxUrlRoute,
  ApiUserSessionRoute: ApiUserSessionRoute,
  ApiUserWithdrawRoute: ApiUserWithdrawRoute,
  ApiPublicFeedKindRoute: ApiPublicFeedKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
